### ISSUE TITLE
Alternative Alleles?

### ISSUE THREAD

**Issue by LauAvinyo** [carjed/helmsman#4]
Hi, 

When trying to run the tutorial (the third cell) I get the following error:
```
Traceback (most recent call last):
  File "helmsman.py", line 273, in <module>
    data = processVCF(args, args.input, subtypes_dict, par)
  File "/home/jovyan/util.py", line 275, in processVCF
    if (record.INFO['AC'] > args.maxac > 0):
TypeError: '>' not supported between instances of 'tuple' and 'int'
```
It seems that when there are alternative alleles the `record.INFO['AC']` is a tuple.
And looking at the code I have seen that in line 280 you skip if the `record.alt` is different than one.

Does this mean that the script cannot handle alternative alleles?

I am running on Linux using the conda environment.

**Comment by carjed** [comment]
Thanks for catching this! The issue relates to handling of multiallelic sites--I had been testing on a VCF with multiallelic sites split into different rows, rather than on a single row with alternative alleles separated by a comma.

The `if-continue` statement in line 280 checks if the *length* of the `record.ALT` object is > 1 to skip these single-row multiallelic SNVs, and should have come before the previous `if-continue` statement.
